### ISSUE TITLE
Readme image - not found

### ISSUE THREAD

**Issue by proteck** [tesujimath/gitmoto#1]
The link for the image is N/D. 

https://github.com/tesujimath/gitmoto/blob/a61b4a7f728dfe28c934aaf39e5c78949872d12f/README.md?plain=1#L3

**Comment by tesujimath** [comment]
Thanks for reporting.  Prompted me to add a screenshot. :sweat_smile: 

Beware that this is in early stage development , so may not be all that useful to you.

Thanks for your interest!
